$ipc = qs -c noctalia-shell ipc call

# Core binds
bind = SUPER, SPACE, exec, $ipc launcher toggle
bind = SUPER, S, exec, $ipc controlCenter toggle
bind = SUPER, comma, exec, $ipc settings toggle

# Media keys
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease

# custom keybinds
bind = Super, D, fullscreen, 1 # Toggle Fullscreen
bind = Super, F, fullscreen # Toggle Fullscreen

# workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, I, movetoworkspace, e-1!

bind = Super, E, exec, dolphin
bind = Super, Return, exec, kitty # kitty

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

bind = SUPER SHIFT CTRL, down, movewindow, mon:d
bind = SUPER SHIFT CTRL, left, movewindow, mon:l
bind = SUPER SHIFT CTRL, right, movewindow, mon:r
bind = SUPER SHIFT CTRL, up, movewindow, mon:u

bind = SUPER, Q, killactive

bind = SUPER SHIFT, left, movewindow, l
binde = SUPER SHIFT, minus, resizeactive, 0 -10%
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bindd = SUPER, code:20, Expand window left, resizeactive, -100 0
bindd = SUPER, code:21, Shrink window left, resizeactive, 100 0
bind = SUPER, down, movefocus, d
binde = SUPER, equal, resizeactive, 10% 0
bind = SUPER, left, movefocus, l
binde = SUPER, minus, resizeactive, -10% 0
bindmd = SUPER, mouse:272, Move window, movewindow
bindmd = SUPER, mouse:273, Resize window, resizewindow
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u

bind = Super Shift, V, exec, pwvucontrol # Volume Control Panel
bind = CTRL ALT, Delete, exec, $ipc sessionMenu toggle
