# Hyprland Configuration
# https://wiki.hypr.land/Configuring/

source = ./env.conf
source = ./startup.conf
source = ./keyboard.conf
source = ./visuals.conf
source = ./misc.conf
source = ./rules.conf

# DMS windows floating by default
source = ./dms/colors.conf
source = ./dms/outputs.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
source = ./dms/binds.conf
# nwg-displays support
#source = ~/.config/hypr/keyboard.conf
