# Hyprland Configuration
# https://wiki.hypr.land/Configuring/

source = ./env.conf
source = ./startup.conf
source = ./keyboard.conf
source = ./binds.conf
source = ./layouts.conf
source = ./misc.conf
source = ./rules.conf
source = ./monitors.conf
source = ./workspaces.conf

# DMS windows floating by default
# source = ./noctalia/layout.conf
# source = ./noctalia/binds.conf
