-- Generated by nwg-displays on 2026-04-28 at 20:38:39.
hl.monitor({ output = "DP-1", mode = "2560x1440@143.97", position = "0x0", scale = 1.0 })
hl.monitor({ output = "DP-2", mode = "2560x1440@164.83", position = "2561x0", scale = 1.0 })
-- hl.monitor({ output = "DP-1", mode = "2560x1440@143.97", position = "0x0", scale = 1.0, bitdepth = 10, cm = "hdr", sdrbrightness = 1.2 })
