# ==================
# STARTUP APPS
# ==================
exec-once = sleep 1 && dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = steam -silent
exec-once = sleep 2 && Telegram -startintray
exec-once = sleep 2 && discord --start-minimized
